### ISSUE TITLE
0.3 saga meta-ticket

### ISSUE THREAD

**Issue by jholman** [garrettgsb/midas#61]
- [ ] views and stuff
  - [ ] Map background
  - [ ] Icons on the map for your assets: mine, wagon, and market
  - [ ] Sidebar, with entries for your assets: mine, wagon, and vendor?
  - [ ] Modals for your assets:
    - [ ] mine modal can harvest
    - [ ] wagon modal can goto
    - [ ] vendor modal can set prices
    - [ ] all modals (of things with RPs) can transload (to other co-located things with RPs)
- [ ] models and stuff
  - [ ] Resource Pools
  - [ ] Vendors
  - [ ] Wagon
  - [ ] Mine
  - [ ] Market
